### ISSUE TITLE
YYYY/MMDD 형태로 이미지 폴더 관리하기

### ISSUE THREAD

**Issue by corazzon** [Kernel360/blog-image#3]
YYYY/MMDD 형태의 구조로 운영을 했으면합니다.
앞으로도 꾸준히 운영할 계획이라 지난 번 PR 코멘트로 남겼었는데 ( https://github.com/Kernel360/blog-image/pull/2 ) 못보신거 같아요.
@stoneHee99 @anso33 부탁드려요!

**Comment by anso33** [comment]
월요일까지 반영하겠습니다!!

**Comment by corazzon** [comment]
고맙습니다 :)

**Comment by anso33** [comment]
반영했습니다!
